import { Inter } from "next/font/google";
import Link from "next/link";
import NavBar from "../components/navbar";
import Footer from "../components/footer";
//const inter = Inter({ subsets: ["latin"] });

import "../static/styles/Main.style.scss";

export const metadata = {
  title: "Quizaida",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="app">
        <NavBar/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
